# Generated by Django 4.1.1 on 2022-09-23 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_improvisationentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='improvisationentry',
            options={'verbose_name_plural': 'Improvisation entries'},
        ),
    ]
