# Generated by Django 4.1.1 on 2022-10-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_improvisationtopic_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='improvisationtopic',
            old_name='text',
            new_name='title',
        ),
        migrations.AddField(
            model_name='improvisationtopic',
            name='key',
            field=models.CharField(default='A Major', max_length=500),
            preserve_default=False,
        ),
    ]
