# Generated by Django 4.1.1 on 2022-10-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_rename_text_improvisationtopic_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='improvisationtopic',
            name='key',
            field=models.CharField(choices=[('a major', 'A Major'), ('a minor', 'A Minor'), ('b major', 'B Major'), ('b major', 'B Major')], default='C Major', max_length=500),
        ),
    ]
