# Generated by Django 4.1.1 on 2022-10-10 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0006_alter_improvisationtopic_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='improvisationtopic',
            name='scale',
            field=models.CharField(choices=[('major', 'Major'), ('minor', 'Minor'), ('melodic', 'Melodic'), ('harmonic', 'Harmonic')], default='Major', max_length=500),
        ),
        migrations.AlterField(
            model_name='improvisationtopic',
            name='key',
            field=models.CharField(choices=[('a', 'A'), ('a#', 'A#'), ('b', 'B'), ('c', 'C'), ('c#', 'C#'), ('d', 'D'), ('d#', 'D#'), ('e', 'E'), ('f', 'F'), ('f#', 'F#'), ('g', 'G'), ('g#', 'G#')], default='C Major', max_length=500),
        ),
    ]
