# Generated by Django 4.1.1 on 2022-10-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0007_improvisationtopic_scale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='improvisationtopic',
            name='chords',
            field=models.JSONField(default='C Major'),
            preserve_default=False,
        ),
    ]
