# Generated by Django 4.1.1 on 2022-10-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0008_improvisationtopic_chords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fretboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('dominant', models.ImageField(blank=True, upload_to='media')),
                ('dominant4', models.ImageField(blank=True, upload_to='media')),
                ('frets', models.ImageField(blank=True, upload_to='media')),
            ],
        ),
    ]
