# Generated by Django 4.1.1 on 2022-10-23 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0009_fretboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='fretboard',
            name='pentatonic',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
